#!/bin/bash

# Change the screen brightness. 
# Usage: 
#	brightness ([value from 0 to 100]|+|-)
# If no input, print the current brighness percentage
# If input is a number, it is assumed that it's a value from 0 to 100 (percentage)
# If input is + or -, it is assumed that the user wants an increase-decrease of $step units in percentage
isNumber() {
	if [ "$1" -eq "$1" ] 2>/dev/null; then
		return 1
	else
		return 0
	fi
}
constrain(){
	# constrain(a, b, c), constrains value a between b and c
	input_1="$1"
	input_2="$2"
	input_3="$3"
	isNumber "$input_1"
	is_1_number="$?"
	isNumber "$input_2"
	is_2_number="$?"
	isNumber "$input_3"
	is_3_number="$?"
	if [ "$is_1_number" == 0 ] || [ "$is_2_number" == 0 ] || [ "$is_3_number" == 0 ] ; then
		>&2 echo "constrain() must receive 3 numbers" 
		return 1
	fi
	if [ "$input_1" -lt "$input_2" ]; then
		echo "$input_2"
		return 0
	elif [ "$input_1" -gt "$input_3" ]; then
		echo "$input_3"
		return 0
	else
		echo "$input_1"
		return 0
	fi
}
change_brightness(){

	# Get backlight info
	DIR="/sys/class/backlight/intel_backlight"
	# Current raw value of brightness
	CURRENT_VAL_RAW="$( cat "$DIR/brightness")"
	# Max raw value
	MAX_VAL_RAW="$( cat "$DIR/max_brightness")"
	input="$1"
	# Check if it's empty
	if [ "$input" == "" ]; then
		CURRENT_BRIGHTNESS_PERCENT="$(($CURRENT_VAL_RAW*100/$MAX_VAL_RAW + 1))"
		CURRENT_BRIGHTNESS_PERCENT="$(constrain $CURRENT_BRIGHTNESS_PERCENT 0 100)"
		echo "Current brightness: $CURRENT_BRIGHTNESS_PERCENT"
		return
	fi
	# Case for - or +
	RAW_STEP="$((MAX_VAL_RAW/40))"
	NEW_VAL_RAW=CURRENT_VAL_RAW
	# if is not a number, error
	isNumber $input
	if [ "$?" == "0" ]; then
		if [ "$input" == "+" ]; then
			# Brightness up
			NEW_VAL_RAW="$(($CURRENT_VAL_RAW+$RAW_STEP))"
			NEW_VAL_RAW="$(constrain $NEW_VAL_RAW 0 $MAX_VAL_RAW)"
		elif [ "$input" == "-" ]; then
			# Brightness down
			NEW_VAL_RAW="$(($CURRENT_VAL_RAW-$RAW_STEP))"
			NEW_VAL_RAW="$(constrain $NEW_VAL_RAW 1 $MAX_VAL_RAW)"
		else
			echo "Error: '$input' is not a number"
			return
		fi
	else
		# It's a number. Check if number is within accepted range
		if [ "$input" -gt 100 ] || [ "$input" -lt 0 ]; then
			echo "Error: Value must be between 0 and 100"
			return
		fi
		NEW_VAL_RAW="$(($MAX_VAL_RAW*$input/100))"
	fi
	# Convert percentage to actual value
	NEW_VAL_PERCENT="$(($NEW_VAL_RAW*100/$MAX_VAL_RAW + 1))"
	NEW_VAL_PERCENT="$(constrain $NEW_VAL_PERCENT 0 100)"
	if [ "$NEW_VAL_RAW" -eq "0" ]; then
		NEW_VAL_RAW="1"
		NEW_VAL_PERCENT="minimum"
	else
		NEW_VAL_PERCENT="$NEW_VAL_PERCENT%"
	fi
	# Set brightness
	#  sh -c 'echo $input > "$DIR/brightness"'
	echo $NEW_VAL_RAW  | tee "$DIR/brightness" > /dev/null
	echo "Brightness set to $NEW_VAL_PERCENT ($NEW_VAL_RAW)"
	unset DIR
	unset CURRENT_VAL_RAW
	unset MAX_VAL_RAW
	unset NEW_VAL_RAW
	unset NEW_VAL_PERCENT
	unset RAW_STEP
	unset input
}
change_brightness $1 $2 $3
