#!/bin/bash
## cloc-git
## Count lines of code of a git repository
## Usage:
## 		cloc-git URL_TO_REPO

git clone --depth 1 "$1" temp-linecount-repo &&
  printf "('temp-linecount-repo' will be deleted automatically)\n\n\n" &&
  cloc temp-linecount-repo &&
  rm -rf temp-linecount-repo