#!/bin/bash

# Update folders
# This script REPLACES the typical folders generated by ubuntu with the shared ones
# indicated by the custom environment variable SHARED_FS

# check if an environment file exists
[[ ! -f "$HOME/.bash_env" ]] && echo "Error: No .bash_env file found" && exit
. .bash_env
# check if shared filesystem is defined
[[ "$SHARED_FS" == "" ]] && echo "Error: Shared filesystem not defined" && exit
# check if defined filesystem exists
[[ ! -f "$SHARED_FS" ]] && echo "Error: Filesystem doesn't exist!" && exit

# Verify user's will to go ahead
echo ""